apiVersion: v1
kind: Secret
metadata:
  name: payflow-secrets
type: Opaque
stringData:
  POSTGRES_USER: payflow
  POSTGRES_PASSWORD: payflow_secret
  POSTGRES_DB: payflow
  DATABASE_URL: postgres://payflow:payflow_secret@postgres:5432/payflow?sslmode=disable
